import { Product } from "@/types";

export const mockProducts: Product[] = [
  {
    id: "1",
    name: "Velvet Noir",
    slug: "velvet-noir",
    description: "A deeply intoxicating blend of black plum, dark patchouli, and vanilla absolute.",
    price: 45,
    comparePrice: null,
    images: ["/images/dark_moody_candle.png"],
    scent: "Black Plum, Patchouli, Vanilla",
    size: ["100ml", "200ml", "300ml"],
    burnTime: "45-50 hours",
    ingredients: "100% natural soy wax, premium botanical oils, cotton wick.",
    howToUse: "Trim wick to 5mm before every burn. Burn for 2-3 hours at a time.",
    stock: 100,
    featured: true,
    bestseller: true,
    isNew: false,
    collectionId: "c1",
    createdAt: new Date(),
  },
  {
    id: "2",
    name: "Wild Peony",
    slug: "wild-peony",
    description: "The essence of a spring garden in full bloom.",
    price: 42,
    comparePrice: null,
    images: ["/images/floral_candle.png"],
    scent: "Peony, Wild Rose, Green Stem",
    size: ["200ml"],
    burnTime: "45-50 hours",
    ingredients: "100% natural soy wax, premium botanical oils, cotton wick.",
    howToUse: "Trim wick to 5mm before every burn. Burn for 2-3 hours at a time.",
    stock: 100,
    featured: true,
    bestseller: false,
    isNew: true,
    collectionId: "c2",
    createdAt: new Date(),
  },
  {
    id: "3",
    name: "Coastal Sage",
    slug: "coastal-sage",
    description: "Like a breath of fresh ocean air.",
    price: 38,
    comparePrice: 45,
    images: ["/images/fresh_clean_candle.png"],
    scent: "Sea Salt, Sage, Driftwood",
    size: ["200ml"],
    burnTime: "45-50 hours",
    ingredients: "100% natural soy wax, premium botanical oils, cotton wick.",
    howToUse: "Trim wick to 5mm before every burn. Burn for 2-3 hours at a time.",
    stock: 100,
    featured: true,
    bestseller: true,
    isNew: false,
    collectionId: "c3",
    createdAt: new Date(),
  },
  {
    id: "4",
    name: "Cashmere Woods",
    slug: "cashmere-woods",
    description: "Wrap yourself in the warmth of toasted sandalwood, amber, and soft musk.",
    price: 48,
    comparePrice: null,
    images: ["/images/warm_cosy_candle.png"],
    scent: "Sandalwood, Amber, Musk",
    size: ["200ml", "300ml"],
    burnTime: "45-50 hours",
    ingredients: "100% natural soy wax, premium botanical oils, cotton wick.",
    howToUse: "Trim wick to 5mm before every burn. Burn for 2-3 hours at a time.",
    stock: 100,
    featured: true,
    bestseller: false,
    isNew: false,
    collectionId: "c4",
    createdAt: new Date(),
  },
];

export const mockCollections = [
  {
    id: "c1",
    name: "Dark & Moody",
    slug: "dark-moody",
    description: "Rich, complex, and deeply atmospheric.",
    image: "/images/dark_moody_candle.png",
    products: [mockProducts[0]],
  },
  {
    id: "c2",
    name: "Floral",
    slug: "floral",
    description: "Soft, delicate, and blooming with botanical notes.",
    image: "/images/floral_candle.png",
    products: [mockProducts[1]],
  },
  {
    id: "c3",
    name: "Fresh & Clean",
    slug: "fresh-clean",
    description: "Crisp, airy, and revitalizing.",
    image: "/images/fresh_clean_candle.png",
    products: [mockProducts[2]],
  },
  {
    id: "c4",
    name: "Warm & Cosy",
    slug: "warm-cosy",
    description: "Comforting, familiar, and inviting.",
    image: "/images/warm_cosy_candle.png",
    products: [mockProducts[3]],
  },
];
